Feature/menu
whiteroma/black-and-white pull request #5
Opened 2022-05-28 18:33 UTC by AlexNuzhdov

2022-05-28 18:38 UTC, whiteroma requested changes
путь к свг

2022-05-29 17:09 UTC, AlexNuzhdov commented
Исправил путь к svg и добавил меню

2022-05-29 20:58 UTC, whiteroma approved these changes

2022-05-29 21:04 UTC, whiteroma approved these changes

2022-05-29 21:37 UTC, merged